### ISSUE TITLE
Ability to get list of actives games for user

### ISSUE THREAD

**Issue by jakejgordon** [JoyfulBits/fungus_toast#19]
As a client app
I can retrieve a list of active games for the current user (including a flag indicating whether I can play my turn)
So that I can allow the client to to pick which game they want to play

(copy/paste from the Google drive document):

GET /api/games?userName=FungusMungus&active=1

Get a list of active games for the specified user

Example JSON response:
```
{
   "Games":[
      {
         "id":2391,
         "numberOfHumanPlayers":2,
         "numberOfAiPlayers":1,
         "dateCreated":"2019-02-07",
         "nextRoundAvailable":true
      },
      {
         "id":2392,
         "numberOfHumanPlayers":4,
         "numberOfAiPlayers":0,
         "dateCreated":"2019-02-08",
         "nextRoundAvailable":false
      }
   ]
}
```

**Comment by Serneum** [comment]
This should be pretty easy to do. Is a game active only if it is in the "Started" state?
